fixing "AttributeError: 'DataFrame' object has no attribute 'tolist' previously a single column DataFrame worked fine with .tolist. converting from Df.tolist to Df.values.tolist